databases:
  - name: drive_share
    databaseName: drive_share
    user: drive_share_user

services:
  - type: web
    name: drive_share_app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: drive_share
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false